packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - "esbuild"
  - "msgpackr-extract"
  - "prisma"
  - "sharp"
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
