/**
 * Route manifest — the allowlist `guide_workflow` and starters use to build
 * navigation. Never generated by the model; deep links must resolve here.
 * `minRole` uses MemberRole names; absence means any active member/visitor.
 */
import type { MyraPrincipal } from "./contracts"

export interface RouteEntry {
  path: string
  surface: "marketing" | "app"
  label: string
  description: string
  /** Minimum MemberRole for app routes; undefined = any member/public. */
  minRole?: string
}

export const ROUTE_MANIFEST: readonly RouteEntry[] = [
  // Marketing surface
  { path: "/", surface: "marketing", label: "Home", description: "LyraShield AI homepage" },
  { path: "/pricing", surface: "marketing", label: "Pricing", description: "Cloud plans, minute packs, trial and Local availability" },
  { path: "/scan", surface: "marketing", label: "Lite Check", description: "Free passive public-surface check" },
  { path: "/tools", surface: "marketing", label: "Free tools", description: "Browser-local security tools" },
  { path: "/docs/integrations", surface: "marketing", label: "Integration guides", description: "CLI, MCP, GitHub Action and agent client setup" },
  { path: "/support", surface: "marketing", label: "Support", description: "Contact support and security reporting" },
  { path: "/demo", surface: "marketing", label: "Book a demo", description: "Schedule a product walkthrough" },
  { path: "/methodology", surface: "marketing", label: "Methodology", description: "How scans, evidence and retests work" },
  { path: "/compare", surface: "marketing", label: "Comparisons", description: "LyraShield vs other tools" },
  // App surface
  { path: "/dashboard", surface: "app", label: "Dashboard", description: "Posture, next action and activity" },
  { path: "/dashboard/targets", surface: "app", label: "Targets", description: "Manage scan targets" },
  { path: "/dashboard/scans", surface: "app", label: "Scans", description: "Scan history and status" },
  { path: "/dashboard/findings", surface: "app", label: "Findings", description: "Detected issues and evidence state" },
  { path: "/dashboard/schedules", surface: "app", label: "Schedules", description: "Recurring scan schedules", minRole: "MEMBER" },
  { path: "/dashboard/settings", surface: "app", label: "Settings", description: "Workspace settings and connections" },
  { path: "/dashboard/billing", surface: "app", label: "Billing", description: "Plan, minutes and packs", minRole: "BILLING_ADMIN" },
  { path: "/dashboard/admin/support", surface: "app", label: "Support inbox", description: "Platform-operator support console", minRole: "OWNER" },
]

const ROLE_RANK: Record<string, number> = {
  VIEWER: 10,
  AUDITOR: 15,
  EXTERNAL_PENTESTER: 20,
  MEMBER: 30,
  DEVELOPER: 40,
  BILLING_ADMIN: 60,
  APPSEC_MANAGER: 70,
  SECURITY_ADMIN: 75,
  ADMIN: 80,
  OWNER: 100,
}

/** Routes a principal may navigate to. Never leaks restricted routes. */
export function routesForPrincipal(
  principal: Pick<MyraPrincipal, "kind"> & { role?: string | null },
  surface: "marketing" | "app"
): RouteEntry[] {
  return ROUTE_MANIFEST.filter((route) => {
    if (route.surface !== surface) return false
    if (!route.minRole) return true
    if (principal.kind !== "user" && principal.kind !== "operator") return false
    if (principal.kind === "operator") return true
    const rank = ROLE_RANK[principal.role ?? ""] ?? 0
    return rank >= (ROLE_RANK[route.minRole] ?? Number.POSITIVE_INFINITY)
  })
}

/** True when the path is a manifest route the principal's role may see. */
export function routeAllowedForPrincipal(
  path: string,
  principal: Pick<MyraPrincipal, "kind"> & { role?: string | null },
  surface: "marketing" | "app"
): boolean {
  const route = ROUTE_MANIFEST.find((r) => r.path === path && r.surface === surface)
  if (!route) return false
  if (!route.minRole) return true
  if (principal.kind === "operator") return true
  if (principal.kind !== "user") return false
  const rank = ROLE_RANK[principal.role ?? ""] ?? 0
  return rank >= (ROLE_RANK[route.minRole] ?? Number.POSITIVE_INFINITY)
}

/** Validate a route is present in the manifest (blocks model-invented links). */
export function isManifestRoute(path: string, surface?: "marketing" | "app"): boolean {
  return ROUTE_MANIFEST.some(
    (r) => r.path === path && (!surface || r.surface === surface)
  )
}
