import { getFixProposal, createAndSendNotification } from "@lyrashield/db"
import { prisma } from "@lyrashield/db"
import { requirePermission } from "@lyrashield/auth/server"
import { PERMISSIONS } from "@lyrashield/auth"
import { sendNotification, type NotificationChannel } from "@lyrashield/integrations"
import {
  getDefaultBranch,
  getBranchRefSha,
  createBranch,
  createOrUpdateFile,
  createPullRequest,
} from "@lyrashield/integrations"
import { logger } from "@lyrashield/logger"
import { authErrorResponse } from "../../../../../lib/api-auth"
import { apiError, apiSuccess } from "../../../../../lib/api-response"
import { z } from "zod"

const MAX_FILE_CONTENT_BYTES = 10 * 1024 * 1024

const CreatePRSchema = z.object({
  workspaceId: z.string().min(1),
  filePath: z
    .string()
    .min(1, "filePath is required")
    .refine((p) => !p.includes("..") && !p.startsWith("/"), "Invalid file path"),
  fileContent: z
    .string()
    .min(1, "fileContent is required")
    .refine(
      (c) => Buffer.byteLength(c, "utf8") <= MAX_FILE_CONTENT_BYTES,
      "File content too large (max 10MB)"
    ),
  commitMessage: z.string().min(1, "commitMessage is required"),
  prTitle: z.string().min(1, "prTitle is required"),
  prBody: z.string().optional(),
})

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params

  try {
    const body = await request.json()
    const parsed = CreatePRSchema.safeParse(body)

    if (!parsed.success) {
      return apiError("INVALID_PARAM", parsed.error.issues[0]?.message ?? "Invalid input", 400)
    }

    const { workspaceId, filePath, fileContent, commitMessage, prTitle, prBody } = parsed.data

    const { session } = await requirePermission(workspaceId, PERMISSIONS.fix.createPr)

    const proposal = await getFixProposal(id, workspaceId)
    if (!proposal) {
      return apiError("PROPOSAL_NOT_FOUND", "Fix proposal not found", 404)
    }

    const finding = await prisma.finding.findFirst({
      where: { id: proposal.findingId, workspaceId, deletedAt: null },
      include: {
        target: true,
      },
    })

    if (!finding || !finding.target) {
      return apiError("TARGET_NOT_FOUND", "Finding has no associated target", 400)
    }

    const target = finding.target
    if (!target.repoOwner || !target.repoName) {
      return apiError("REPO_NOT_FOUND", "Target is not a GitHub repo", 400)
    }

    const integration = await prisma.integration.findFirst({
      where: {
        workspaceId,
        type: "GITHUB",
        status: "active",
        deletedAt: null,
      },
    })

    if (!integration || !integration.externalId) {
      return apiError("NO_GITHUB_INTEGRATION", "GitHub App not installed for this workspace", 400)
    }

    const installationId = parseInt(integration.externalId, 10)
    const { repoOwner, repoName } = target

    const baseBranch =
      target.branch ?? (await getDefaultBranch(installationId, repoOwner, repoName))
    const branchName = `lyrasec/fix-${proposal.id}`
    const sha = await getBranchRefSha(installationId, repoOwner, repoName, baseBranch)
    await createBranch(installationId, repoOwner, repoName, branchName, sha)
    await createOrUpdateFile(
      installationId,
      repoOwner,
      repoName,
      filePath,
      fileContent,
      commitMessage,
      branchName
    )

    const prResult = await createPullRequest(
      installationId,
      repoOwner,
      repoName,
      prTitle,
      prBody ?? `Fix for: ${finding.title}\n\nGenerated by LyraSec AI`,
      branchName,
      baseBranch
    )

    const prRecord = await prisma.$transaction(async (tx) => {
      const record = await tx.pullRequest.create({
        data: {
          fixProposalId: proposal.id,
          provider: "github",
          repoOwner,
          repoName,
          branchName,
          prNumber: prResult.number,
          prUrl: prResult.url,
          status: "open",
        },
      })

      await tx.fixProposal.update({
        where: { id: proposal.id },
        data: { status: "pr_opened" },
      })

      await tx.finding.update({
        where: { id: finding.id },
        data: { status: "PR_OPENED" },
      })

      await tx.auditLog.create({
        data: {
          workspaceId,
          actorUserId: session.userId,
          action: "fix_pr.created",
          resourceType: "pull_request",
          resourceId: record.id,
        },
      })

      return record
    })

    logger.info("Fix PR created", {
      proposalId: proposal.id,
      prNumber: prResult.number,
      prUrl: prResult.url,
    })

    try {
      const workspace = await prisma.workspace.findFirst({
        where: { id: workspaceId },
        select: { name: true },
      })
      const notifTitle = `Fix PR Created — ${finding.title}`
      const notifBody = `A pull request has been created for: ${finding.title}\n\nPR URL: ${prResult.url}`
      await createAndSendNotification({
        workspaceId,
        type: "fix.pr_created",
        title: notifTitle,
        body: notifBody,
        workspaceName: workspace?.name,
        sendFn: (channel, payload) => sendNotification(channel as NotificationChannel, payload),
      })
    } catch (notifError) {
      logger.warn("Failed to send fix PR notification", { error: String(notifError) })
    }

    return apiSuccess({
      prNumber: prResult.number,
      prUrl: prResult.url,
      branchName,
      prId: prRecord.id,
    })
  } catch (error) {
    const authErr = authErrorResponse(error)
    if (authErr) return authErr
    logger.error("Failed to create fix PR", { error: String(error) })
    return apiError("INTERNAL_ERROR", "Failed to create fix PR", 500)
  }
}
